import { CanvasElement, CustomTemplateData } from '@/types/template-builder';

export const TEMPLATE_PRESETS: CustomTemplateData[] = [
  {
    id: 'preset-google-quad',
    name: 'Google Signature Quad-Color Stand',
    aspect: 'square',
    width: 500,
    height: 500,
    background: 'conic-gradient(from 12deg at 50% 50%, #EA4335 0deg 90deg, #FBBC05 90deg 180deg, #34A853 180deg 270deg, #4285F4 270deg 360deg)',
    elements: [
      {
        id: 'white-card-bg',
        type: 'shape',
        x: 25,
        y: 135,
        width: 450,
        height: 340,
        zIndex: 1,
        backgroundColor: '#ffffff',
        borderRadius: 28,
        boxShadow: '0 10px 25px rgba(0,0,0,0.1)',
      },
      {
        id: 'logo-circle-bg',
        type: 'shape',
        x: 185,
        y: 70,
        width: 130,
        height: 130,
        zIndex: 2,
        backgroundColor: '#ffffff',
        borderRadius: 65,
        boxShadow: '0 4px 12px rgba(0,0,0,0.08)',
      },
      {
        id: 'google-g-logo',
        type: 'google_logo',
        content: 'g_icon',
        x: 215,
        y: 100,
        width: 70,
        height: 70,
        zIndex: 3,
      },
      {
        id: 'header-subtitle',
        type: 'text',
        content: 'review us',
        x: 50,
        y: 200,
        width: 400,
        height: 30,
        zIndex: 3,
        fontSize: 24,
        fontWeight: '400',
        textAlign: 'center',
        color: '#111827',
        fontFamily: 'Outfit',
      },
      {
        id: 'header-title',
        type: 'text',
        content: 'on Google',
        x: 50,
        y: 230,
        width: 400,
        height: 48,
        zIndex: 3,
        fontSize: 44,
        fontWeight: '700',
        textAlign: 'center',
        color: '#000000',
        fontFamily: 'Outfit',
        letterSpacing: -1,
      },
      {
        id: 'tap-instruction',
        type: 'text',
        content: 'TAP YOUR PHONE',
        x: 50,
        y: 295,
        width: 160,
        height: 20,
        zIndex: 3,
        fontSize: 12,
        fontWeight: '700',
        textAlign: 'center',
        color: '#111827',
        fontFamily: 'Outfit',
        letterSpacing: 0.5,
      },
      {
        id: 'tap-nfc-icon',
        type: 'nfc_icon',
        iconVariant: 'hand_phone',
        x: 75,
        y: 320,
        width: 110,
        height: 80,
        zIndex: 3,
      },
      {
        id: 'divider-or',
        type: 'divider_or',
        content: 'OR',
        x: 235,
        y: 310,
        width: 30,
        height: 90,
        zIndex: 3,
        color: '#111827',
      },
      {
        id: 'scan-instruction',
        type: 'text',
        content: 'SCAN QR',
        x: 290,
        y: 295,
        width: 160,
        height: 20,
        zIndex: 3,
        fontSize: 12,
        fontWeight: '700',
        textAlign: 'center',
        color: '#111827',
        fontFamily: 'Outfit',
        letterSpacing: 0.5,
      },
      {
        id: 'qr-code-box',
        type: 'qr',
        x: 330,
        y: 320,
        width: 80,
        height: 80,
        zIndex: 3,
        borderRadius: 8,
        borderColor: '#aaaaaa',
        borderWidth: 1,
        backgroundColor: '#ffffff',
      },
      {
        id: 'footer-business',
        type: 'text',
        content: '{{businessName}}',
        x: 50,
        y: 430,
        width: 400,
        height: 24,
        zIndex: 3,
        fontSize: 14,
        fontWeight: '700',
        textAlign: 'center',
        color: '#111827',
        fontFamily: 'Outfit',
      },
    ],
  },
  {
    id: 'preset-etta-white',
    name: 'Minimalist White L-Stand (eTTa Style)',
    aspect: 'square',
    width: 500,
    height: 500,
    background: '#fcfcfc',
    elements: [
      {
        id: 'business-header',
        type: 'text',
        content: '{{businessName}}',
        x: 50,
        y: 35,
        width: 400,
        height: 30,
        zIndex: 2,
        fontSize: 18,
        fontWeight: '700',
        textAlign: 'center',
        color: '#111827',
        fontFamily: 'Outfit',
      },
      {
        id: 'stars-rating',
        type: 'stars',
        x: 180,
        y: 75,
        width: 140,
        height: 30,
        zIndex: 2,
        starCount: 5,
        starFilled: false,
        starColor: '#111827',
      },
      {
        id: 'review-us-on',
        type: 'text',
        content: 'review us on',
        x: 50,
        y: 120,
        width: 400,
        height: 25,
        zIndex: 2,
        fontSize: 20,
        fontWeight: '400',
        textAlign: 'center',
        color: '#374151',
        fontFamily: 'Outfit',
      },
      {
        id: 'google-wordmark',
        type: 'text',
        content: 'Google',
        x: 50,
        y: 145,
        width: 400,
        height: 50,
        zIndex: 2,
        fontSize: 48,
        fontWeight: '700',
        textAlign: 'center',
        color: '#000000',
        fontFamily: 'Outfit',
        letterSpacing: -1,
      },
      {
        id: 'etta-tap-icon',
        type: 'nfc_icon',
        iconVariant: 'circular_tap',
        x: 90,
        y: 220,
        width: 100,
        height: 90,
        zIndex: 2,
      },
      {
        id: 'etta-tap-text',
        type: 'text',
        content: 'Tap & Hold',
        x: 60,
        y: 320,
        width: 160,
        height: 25,
        zIndex: 2,
        fontSize: 14,
        fontWeight: '600',
        textAlign: 'center',
        color: '#111827',
        fontFamily: 'Outfit',
      },
      {
        id: 'etta-or',
        type: 'text',
        content: 'OR',
        x: 230,
        y: 260,
        width: 40,
        height: 25,
        zIndex: 2,
        fontSize: 13,
        fontWeight: '700',
        textAlign: 'center',
        color: '#9ca3af',
      },
      {
        id: 'etta-qr-box',
        type: 'qr',
        x: 310,
        y: 220,
        width: 90,
        height: 90,
        zIndex: 2,
        borderRadius: 10,
        borderColor: '#cbd5e1',
        borderWidth: 1,
        backgroundColor: '#ffffff',
      },
      {
        id: 'etta-scan-text',
        type: 'text',
        content: 'Scan QR',
        x: 275,
        y: 320,
        width: 160,
        height: 25,
        zIndex: 2,
        fontSize: 14,
        fontWeight: '600',
        textAlign: 'center',
        color: '#111827',
        fontFamily: 'Outfit',
      },
      {
        id: 'etta-footer-text',
        type: 'text',
        content: '{{location}}',
        x: 50,
        y: 430,
        width: 400,
        height: 25,
        zIndex: 2,
        fontSize: 13,
        fontWeight: '400',
        textAlign: 'center',
        color: '#6b7280',
        fontFamily: 'Outfit',
      },
    ],
  },
  {
    id: 'preset-pvc-vertical',
    name: 'Vertical Black Smart NFC Card (CR80)',
    aspect: 'vertical',
    width: 340,
    height: 540,
    background: '#090b11',
    elements: [
      {
        id: 'pvc-nfc-badge',
        type: 'nfc_icon',
        iconVariant: 'nfc_badge',
        x: 265,
        y: 20,
        width: 50,
        height: 40,
        zIndex: 2,
        isDark: true,
      },
      {
        id: 'pvc-google-title',
        type: 'text',
        content: 'Google',
        x: 20,
        y: 90,
        width: 300,
        height: 48,
        zIndex: 2,
        fontSize: 38,
        fontWeight: '700',
        textAlign: 'center',
        color: '#ffffff',
        fontFamily: 'Outfit',
      },
      {
        id: 'pvc-reviews-text',
        type: 'text',
        content: 'Reviews ★★★★★',
        x: 20,
        y: 140,
        width: 300,
        height: 28,
        zIndex: 2,
        fontSize: 16,
        fontWeight: '600',
        textAlign: 'center',
        color: '#e2e8f0',
        fontFamily: 'Outfit',
      },
      {
        id: 'pvc-qr-box',
        type: 'qr',
        x: 85,
        y: 195,
        width: 170,
        height: 170,
        zIndex: 2,
        borderRadius: 16,
        backgroundColor: '#ffffff',
      },
      {
        id: 'pvc-scan-instruction',
        type: 'text',
        content: 'Scan QR Code or NFC',
        x: 20,
        y: 395,
        width: 300,
        height: 30,
        zIndex: 2,
        fontSize: 15,
        fontWeight: '600',
        textAlign: 'center',
        color: '#cbd5e1',
        fontFamily: 'Outfit',
      },
      {
        id: 'pvc-business-name',
        type: 'text',
        content: '{{businessName}}',
        x: 20,
        y: 470,
        width: 300,
        height: 25,
        zIndex: 2,
        fontSize: 13,
        fontWeight: '700',
        textAlign: 'center',
        color: '#94a3b8',
        fontFamily: 'Outfit',
      },
    ],
  },
  {
    id: 'preset-glossy-black',
    name: 'Glossy Black Acrylic Plaque',
    aspect: 'square',
    width: 500,
    height: 500,
    background: '#090b10',
    elements: [
      {
        id: 'black-g-logo',
        type: 'google_logo',
        content: 'g_icon',
        x: 215,
        y: 30,
        width: 70,
        height: 70,
        zIndex: 2,
      },
      {
        id: 'black-5-stars',
        type: 'stars',
        x: 170,
        y: 110,
        width: 160,
        height: 30,
        zIndex: 2,
        starCount: 5,
        starFilled: true,
        starColor: '#FBBC05',
      },
      {
        id: 'black-review-title',
        type: 'text',
        content: 'REVIEW US ON GOOGLE',
        x: 50,
        y: 150,
        width: 400,
        height: 30,
        zIndex: 2,
        fontSize: 16,
        fontWeight: '700',
        textAlign: 'center',
        color: '#ffffff',
        fontFamily: 'Outfit',
        letterSpacing: 2,
      },
      {
        id: 'black-phone-nfc',
        type: 'nfc_icon',
        iconVariant: 'phone_outline',
        x: 100,
        y: 210,
        width: 110,
        height: 140,
        zIndex: 2,
        isDark: true,
      },
      {
        id: 'black-qr-box',
        type: 'qr',
        x: 280,
        y: 210,
        width: 140,
        height: 140,
        zIndex: 2,
        borderRadius: 18,
        backgroundColor: '#ffffff',
      },
      {
        id: 'black-footer',
        type: 'text',
        content: '{{businessName}} • {{location}}',
        x: 50,
        y: 430,
        width: 400,
        height: 25,
        zIndex: 2,
        fontSize: 14,
        fontWeight: '600',
        textAlign: 'center',
        color: '#cbd5e1',
        fontFamily: 'Outfit',
      },
    ],
  },
];
