import { CanvasElement, CustomTemplateData } from '@/types/template-builder';

export const TEMPLATE_PRESETS: CustomTemplateData[] = [
  {
    id: 'preset-google-quad',
    name: 'Google Signature Quad-Color Stand',
    aspect: 'square',
    width: 500,
    height: 500,
    background: 'conic-gradient(from 12deg at 50% 50%, #EA4335 0deg 90deg, #FBBC05 90deg 180deg, #34A853 180deg 270deg, #4285F4 270deg 360deg)',
    elements: [
      {
        id: 'white-card-bg',
        type: 'shape',
        x: 25,
        y: 135,
        width: 450,
        height: 340,
        zIndex: 1,
        backgroundColor: '#ffffff',
        borderRadius: 28,
        boxShadow: '0 10px 25px rgba(0,0,0,0.1)',
      },
      {
        id: 'logo-circle-bg',
        type: 'shape',
        x: 185,
        y: 70,
        width: 130,
        height: 130,
        zIndex: 2,
        backgroundColor: '#ffffff',
        borderRadius: 65,
        boxShadow: '0 4px 12px rgba(0,0,0,0.08)',
      },
      {
        id: 'google-g-logo',
        type: 'google_logo',
        content: 'g_icon',
        x: 215,
        y: 100,
        width: 70,
        height: 70,
        zIndex: 3,
      },
      {
        id: 'header-subtitle',
        type: 'text',
        content: 'review us',
        x: 50,
        y: 200,
        width: 400,
        height: 30,
        zIndex: 3,
        fontSize: 24,
        fontWeight: '400',
        textAlign: 'center',
        color: '#111827',
        fontFamily: 'Outfit',
      },
      {
        id: 'header-title',
        type: 'text',
        content: 'on Google',
        x: 50,
        y: 230,
        width: 400,
        height: 48,
        zIndex: 3,
        fontSize: 44,
        fontWeight: '700',
        textAlign: 'center',
        color: '#000000',
        fontFamily: 'Outfit',
        letterSpacing: -1,
      },
      {
        id: 'tap-instruction',
        type: 'text',
        content: 'TAP YOUR PHONE',
        x: 50,
        y: 295,
        width: 160,
        height: 20,
        zIndex: 3,
        fontSize: 12,
        fontWeight: '700',
        textAlign: 'center',
        color: '#111827',
        fontFamily: 'Outfit',
        letterSpacing: 0.5,
      },
      {
        id: 'tap-nfc-icon',
        type: 'nfc_icon',
        iconVariant: 'hand_phone',
        x: 75,
        y: 320,
        width: 110,
        height: 80,
        zIndex: 3,
      },
      {
        id: 'divider-or',
        type: 'divider_or',
        content: 'OR',
        x: 235,
        y: 310,
        width: 30,
        height: 90,
        zIndex: 3,
        color: '#111827',
      },
      {
        id: 'scan-instruction',
        type: 'text',
        content: 'SCAN QR',
        x: 290,
        y: 295,
        width: 160,
        height: 20,
        zIndex: 3,
        fontSize: 12,
        fontWeight: '700',
        textAlign: 'center',
        color: '#111827',
        fontFamily: 'Outfit',
        letterSpacing: 0.5,
      },
      {
        id: 'qr-code-box',
        type: 'qr',
        x: 330,
        y: 320,
        width: 80,
        height: 80,
        zIndex: 3,
        borderRadius: 8,
        borderColor: '#aaaaaa',
        borderWidth: 1,
        backgroundColor: '#ffffff',
      },
      {
        id: 'footer-business',
        type: 'text',
        content: '{{businessName}}',
        x: 50,
        y: 430,
        width: 400,
        height: 24,
        zIndex: 3,
        fontSize: 14,
        fontWeight: '700',
        textAlign: 'center',
        color: '#111827',
        fontFamily: 'Outfit',
      },
    ],
  },
  {
    id: 'preset-etta-white',
    name: 'Minimalist White L-Stand (eTTa Style)',
    aspect: 'square',
    width: 500,
    height: 500,
    background: '#fcfcfc',
    elements: [
      { id: 'business', type: 'text', content: '{{businessName}}', x: 20, y: 35, width: 460, height: 25, zIndex: 2, fontSize: 20, fontWeight: '700', textAlign: 'center', color: '#111827', fontFamily: 'Outfit' },
      { id: 'rate', type: 'text', content: 'Rate your experience with us', x: 20, y: 65, width: 460, height: 20, zIndex: 2, fontSize: 13, fontWeight: '500', textAlign: 'center', color: '#6b7280', fontFamily: 'Outfit' },
      { id: 'google-wordmark', type: 'google_logo', content: 'google_wordmark', x: 120, y: 95, width: 260, height: 80, zIndex: 2 },
      { id: 'stars-rating', type: 'stars', x: 150, y: 175, width: 200, height: 35, zIndex: 2, starCount: 5, starFilled: true, starColor: '#FBBC05' },
      { id: 'divider-or', type: 'divider_or', content: 'OR', x: 235, y: 250, width: 30, height: 160, zIndex: 3, color: '#9ca3af' },
      { id: 'qr-box', type: 'qr', x: 290, y: 260, width: 140, height: 140, zIndex: 2, borderRadius: 12, borderColor: '#cbd5e1', borderWidth: 1, backgroundColor: '#ffffff' },
      { id: 'qr-text', type: 'text', content: 'SCAN QR', x: 280, y: 415, width: 160, height: 25, zIndex: 2, fontSize: 15, fontWeight: '700', textAlign: 'center', color: '#111827', fontFamily: 'Outfit' },
      { id: 'nfc-icon', type: 'nfc_icon', iconVariant: 'hand_phone', x: 80, y: 275, width: 110, height: 110, zIndex: 2, color: '#3b82f6' },
      { id: 'nfc-text', type: 'text', content: 'TAP PHONE', x: 55, y: 415, width: 160, height: 25, zIndex: 2, fontSize: 15, fontWeight: '700', textAlign: 'center', color: '#3b82f6', fontFamily: 'Outfit' },
      { id: 'footer-loc', type: 'text', content: '{{location}}', x: 20, y: 460, width: 460, height: 20, zIndex: 2, fontSize: 12, fontWeight: '400', textAlign: 'center', color: '#9ca3af', fontFamily: 'Outfit' },
    ],
  },
  {
    id: 'preset-pvc-vertical',
    name: 'Vertical Black Smart NFC Card (CR80)',
    aspect: 'vertical',
    width: 340,
    height: 540,
    background: 'linear-gradient(135deg, #111827 0%, #030712 100%)',
    elements: [
      { id: 'card-business', type: 'text', content: '{{businessName}}', x: 20, y: 35, width: 300, height: 25, zIndex: 2, fontSize: 16, fontWeight: '600', textAlign: 'center', color: '#f3f4f6', fontFamily: 'Outfit', letterSpacing: 1 },
      { id: 'card-accent', type: 'shape', x: 135, y: 70, width: 70, height: 3, zIndex: 2, backgroundColor: '#3b82f6', borderRadius: 2 },
      { id: 'card-g-logo', type: 'google_logo', content: 'g_icon', x: 135, y: 95, width: 70, height: 70, zIndex: 2 },
      { id: 'card-reviews', type: 'text', content: 'GOOGLE REVIEWS', x: 20, y: 180, width: 300, height: 25, zIndex: 2, fontSize: 17, fontWeight: '700', textAlign: 'center', color: '#ffffff', fontFamily: 'Outfit', letterSpacing: 2 },
      { id: 'card-stars', type: 'stars', x: 100, y: 215, width: 140, height: 25, zIndex: 2, starCount: 5, starFilled: true, starColor: '#FBBC05' },
      { id: 'card-qr', type: 'qr', x: 80, y: 270, width: 180, height: 180, zIndex: 2, borderRadius: 12, backgroundColor: '#ffffff' },
      { id: 'card-scan-text', type: 'text', content: 'SCAN OR TAP', x: 20, y: 465, width: 300, height: 20, zIndex: 2, fontSize: 13, fontWeight: '700', textAlign: 'center', color: '#9ca3af', fontFamily: 'Outfit', letterSpacing: 2 },
      { id: 'card-nfc', type: 'nfc_icon', iconVariant: 'hand_phone', x: 125, y: 485, width: 90, height: 50, zIndex: 2, color: '#ffffff' },
    ],
  },
  {
    id: 'preset-glossy-black',
    name: 'Glossy Black Acrylic Plaque',
    aspect: 'square',
    width: 500,
    height: 500,
    background: '#09090b',
    elements: [
      { id: 'border-shape', type: 'shape', x: 15, y: 15, width: 470, height: 470, zIndex: 1, borderWidth: 1, borderColor: '#334155', borderRadius: 24, backgroundColor: 'transparent' },
      { id: 'border-inner', type: 'shape', x: 25, y: 25, width: 450, height: 450, zIndex: 1, borderWidth: 1, borderColor: '#1e293b', borderRadius: 16, backgroundColor: 'transparent' },
      { id: 'g-logo', type: 'google_logo', content: 'google_wordmark', x: 120, y: 70, width: 260, height: 80, zIndex: 2 },
      { id: 'g-stars', type: 'stars', x: 160, y: 155, width: 180, height: 30, zIndex: 2, starCount: 5, starFilled: true, starColor: '#FBBC05' },
      { id: 'nfc-phone', type: 'nfc_icon', iconVariant: 'hand_phone', x: 70, y: 220, width: 140, height: 140, zIndex: 2, color: '#ffffff' },
      { id: 'nfc-txt', type: 'text', content: 'TAP SMARTPHONE', x: 60, y: 380, width: 160, height: 25, zIndex: 2, fontSize: 13, fontWeight: '700', textAlign: 'center', color: '#f8fafc', fontFamily: 'Outfit', letterSpacing: 1 },
      { id: 'qr-box', type: 'qr', x: 290, y: 220, width: 140, height: 140, zIndex: 2, borderRadius: 12, backgroundColor: '#ffffff' },
      { id: 'qr-txt', type: 'text', content: 'SCAN QR CODE', x: 280, y: 380, width: 160, height: 25, zIndex: 2, fontSize: 13, fontWeight: '700', textAlign: 'center', color: '#f8fafc', fontFamily: 'Outfit', letterSpacing: 1 },
      { id: 'div-or', type: 'divider_or', content: 'OR', x: 235, y: 220, width: 30, height: 140, zIndex: 3, color: '#475569' },
      { id: 'plaque-bus', type: 'text', content: '{{businessName}}', x: 20, y: 440, width: 460, height: 20, zIndex: 2, fontSize: 14, fontWeight: '600', textAlign: 'center', color: '#94a3b8', fontFamily: 'Outfit' },
    ],
  },
];
